---
# tasks file for init_master_node
- name: create .kube directory
  become: yes
  become_user: "{{ new_user }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0700

- name: Check that the /etc/kubernetes/admin.conf exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: stat_result

- name: Initialization cluster if /etc/kubernetes/admin.conf is not exists
  shell: kubeadm init --apiserver-advertise-address {{ master_node_ip }} --pod-network-cidr {{ network_cidr }}
  when: not stat_result.stat.exists

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ new_user }}/.kube/config
    remote_src: yes
    owner: "{{ new_user }}"

- name: install Pod network
  become: yes
  become_user: "{{ new_user }}"
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: Get the token for joining the nodes with Kuberentes master
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: Copy join command to local file.
  become: false
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777