---
# tasks file for init_worker_nodes
- name: Copy join command to worker nodes.
  copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: 0777

- name: Join the Worker nodes with master.
  command: sh /tmp/kubernetes_join_command
  register: joined_or_not

- debug:
    msg: "{{ joined_or_not.stdout }}"